package engineering.enums;

public enum Screen {
    LOGIN,
    MUSICIAN_DASHBOARD,
    PROMOTER_DASHBOARD,
    VIEW_ANNOUNCEMENT_DETAILS,
    VIEW_ANNOUNCEMENT_APPLICATIONS,
    VIEW_MY_ANNOUNCEMENTS,
    CREATE_ANNOUNCEMENT
}
