package engineering.enums;

public enum Screen {
    LOGIN,
    MUSICIAN_REGISTRATION,
    PROMOTER_REGISTRATION,
    MUSICIAN_DASHBOARD,
    PROMOTER_DASHBOARD,
    VIEW_ANNOUNCEMENT_DETAILS,
    VIEW_ANNOUNCEMENT_APPLICATIONS,
    VIEW_APPLICATION_DETAILS,
    OPEN_ANNOUNCEMENTS_DISCOVERY,
    CREATE_ANNOUNCEMENT,
    NOTIFICATIONS
}
